services:
  - type: web
    name: video-converter-ffmpeg
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: MAX_RETENTION_MINUTES
        value: "60"
    healthCheckPath: /api/health
    disk:
      name: video-storage
      mountPath: /app/temp_videos
      sizeGB: 10